# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master, workflow-testing ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Converts pushed PDF file to a PNG file
      - name: Convert PDF to PNG
        run: |
          sudo apt-get install poppler-utils
          pdftoppm Nathan_Cheung_Resume_No_Phone.pdf Nathan_Cheung_Resume_Image -png -singlefile
      
      # Pushes PNG file to Github repo to be displayed in README.md
      - name: Push PNG to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.name "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add Nathan_Cheung_Resume_Image.png
          git commit -m "Converted PDF to PNG file"
          git push
          
          
